### ISSUE TITLE
[SDK] Flow Builder Epic

### ISSUE THREAD

**Issue by happie-chappie** [Aroha-Labs/mira-sdk-python#10]
<h2>Overview</h2>
<p>The flow builder part of the SDK is a comprehensive system that allows developers to design, build, and test flows. It provides a structured process for defining flow details, input parameters, multiple components, and output parameters. The system allows for local testing and editing, offering a seamless experience from initial design to functional implementation.</p>
<h2>User Story</h2>
<p>As a developer, I want to create and test complex flows in a single, intuitive interface so that I can quickly design and implement AI-powered solutions for my applications.</p>
<h2>User Journey</h2>
<pre><code class="language-jsx">┌─────────────────────────────────────────────────────────────────────┐
│                          Start Flow Creation                        │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         Define Flow Details                         │
│  ┌───────────────┐ ┌────────────────────┐ ┌────────────────┐        │
│  │   Flow Name   │ │ Flow Description   │ │  Flow Version  │        │
│  └───────────────┘ └────────────────────┘ └────────────────┘        │
│  ┌───────────────────────────────────────────────────────────────┐  │
│  │                         Flow Privacy                          │  │
│  └───────────────────────────────────────────────────────────────┘  │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                          Define Flow Input                          │
│  ┌───────────────┐    ┌────────────────────┐    ┌────────────────┐  │
│  │ Parameter Name│    │     Description    │    │     Format     │  │
│  └───────────────┘    └────────────────────┘    └────────────────┘  │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         Build Components                            │
│  ┌───────────────────────────────────────────────────────────────┐  │
│  │                      For Each Component:                      │  │
│  │  ┌─────────────────────────┐  ┌────────────────────────────┐  │  │
│  │  │    Input Parameters     │  │          Prompt            │  │  │
│  │  │ - Name                  │  │ - Type system prompt       │  │  │
│  │  │ - Reference (Flow input │  └────────────────────────────┘  │  │
│  │  │   or Component output)  │  ┌────────────────────────────┐  │  │
│  │  └─────────────────────────┘  │           Model            │  │  │
│  │  ┌─────────────────────────┐  │ - Specify model to use     │  │  │
│  │  │      Data (Optional)    │  └────────────────────────────┘  │  │
│  │  │ - Reference dataset     │  ┌────────────────────────────┐  │  │
│  │  │   from data manager     │  │     Output Parameter       │  │  │
│  │  └─────────────────────────┘  │ - Name output parameter    │  │  │
│  │                               └────────────────────────────┘  │  │
│  └───────────────────────────────────────────────────────────────┘  │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         Define Flow Output                          │
│  ┌───────────────────────┐    ┌────────────────────────────────┐    │
│  │ Output Parameter Name │    │ Reference (Component Output)   │    │
│  └───────────────────────┘    └────────────────────────────────┘    │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         Test Locally                                │
│  Execute flow in the flow file locally using a single CLI command   │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         Edit Locally                                │
│  Edit flow in one file before testing again                         │
└───────────────────────────────────┬─────────────────────────────────┘
                                    │
                                    ▼
┌─────────────────────────────────────────────────────────────────────┐
│                         End Flow Creation                           │
└─────────────────────────────────────────────────────────────────────┘
</code></pre>
<h2>Elements</h2>

Element | Sub Element | Description
-- | -- | --
Defining flow details | Flow name | Feature to type out the flow name
  | Flow description | Feature to type out the flow descriptiion
  | Flow version | Feature to type of flow version
  | Flow privacy | Privte/public
Defining flow input | - | Feature to define the input parameters for the flow
Name of input parameter |   |  
Description of inout parameter |   |  
Format of inut parameter (string, number, date[dd/mm/yy]) |   |  
Building components | - | Feature to define each component, user may build N number of components
  | Adding input parameters | Feature to define all the input parameters and their reference
name of input parameter |   |  
reference of that parameter (what that value corelates to, it can be a flow input or output of another component) |   |  
  | Adding Prompt | Feature to just type out each prompt within the component, this pormopt will be used as the sytem propmt for that component
  | Adding Model | Feature to type out model for each component
  | Linking Data (optional) | Feature to type out the data set reference stored in the data manager.
This indexed data, is automatically used as a RAG system for that component. |   |  
  | Adding output parameter | Feature to add the output parameter for the component -
Output parameter name |   |  
  |   |  
Defining flow output |   | Feature to define flow output parameters(one flow can have multiple outputs) -
Name of output parameter |   |  
Reference of thaty parameter (this can be the output of any component) |   |  
Test locally | - | Functionality to test the flow in the flow file locally by a single command
Editing locally | - | Functionality to edit the flow then and there in one file before testing it again

<p><strong>Structure of Each flow :</strong></p>
<ul>
<li>Flow details
<ul>
<li>flow name</li>
<li>flow description</li>
<li>FLow version</li>
</ul>
</li>
<li>Flow inputs
<ul>
<li>Input N
<ul>
<li>Name</li>
<li>Details</li>
<li>format</li>
</ul>
</li>
</ul>
</li>
<li>Flow component N
<ul>
<li>Inputs
<ul>
<li>Input N</li>
<li>Input Reference</li>
</ul>
</li>
<li>Model</li>
<li>Prompt (locally typed out)</li>
<li>Data set reference</li>
<li>Output
<ul>
<li>Parameter name</li>
</ul>
</li>
</ul>
</li>
<li>Flow outputs
<ul>
<li>Output N
<ul>
<li>Name</li>
<li>Parameter Reference</li>
</ul>
</li>
</ul>
</li>
</ul>

<h2>Tasks</h2>

- [ ] Functionality to define flow details (name, description, version, privacy)
- [ ] Functionality to set up flow input parameters
- [ ] Functionality to create and configure multiple components within a flow
- [ ] Functionality to define flow output parameters
- [ ] Functionality to add prompts locally to components
- [ ] Functionality to define Component inputs and outputs along with the ability to reference component inputs to flow inputs or outputs of other components
- [ ] Functionality to select models for components
- [ ] Functionality to link data sources to components
- [ ] Functionality to test flows locally
- [ ] Functionality to edit flows in-place
- [ ] Functionality to manage flow versions
